### ISSUE TITLE
Full example with request itself ?

### ISSUE THREAD

**Issue by sylvain-ri** [ahmednafies/pydantic-webargs#9]
I love the combination of pydantic with http requests. While i'm experienced with Python, I'm pretty new to the Web, and I would like to see more detailed instructions to be able to use your library.

What is the exact request that you can send in your two examples ? Something like 
```python
request("/post-request", 
        query={"name": "my_name"}, 
        body={"age": "30})
```

**Comment by nf1s** [comment]
perhaps you can check the tests
https://github.com/nf1s/pydantic-webargs/blob/master/tests/test_webargs.py
